apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: sample-app-kotlin-gradle
spec:
  version: "v1.0.0"
  image: "openfunction/buildpacks-sample-apps-kotlin-gradle:latest"
  port: 8080 # default to 8080
  build:
    builder: "cnbs/sample-builder:alpine"
    srcRepo:
      url: "https://github.com/buildpacks/samples.git"
      sourceSubPath: "apps/kotlin-gradle"
    registry:
      url: "https://index.docker.io/v1/"
      account:
        name: "basic-user-pass"
        key: "username"
  #serving:
    #runtime: "Knative" # default to Knative
