# permissions for end users to view builders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builder-viewer-role
rules:
- apiGroups:
  - openfunction.io
  resources:
  - builders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openfunction.io
  resources:
  - builders/status
  verbs:
  - get
