# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servings.core.openfunction.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: <caBundle-placement>
        service:
          namespace: openfunction
          name: webhook-service
          path: /convert
#        url: "https://<node-ip>:9443/convert"
      conversionReviewVersions:
      - v1
