apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: autoscaling-producer
spec:
  version: "v1.0.0"
  image: openfunctiondev/v1beta1-autoscaling-producer:latest
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/builder-go:latest
    env:
      FUNC_NAME: "Producer"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Async/pubsub/producer"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: Always
    runtime: "Async"
    params:
      OUTPUT_NAME: subscriber
      TOPIC_NAME: "sample-topic"
      NUMBER_OF_PUBLISHERS: "2"
      PUBLISHERS_FREQ: "100ms"
      PUBLISHERS_DELAY: "10s"
      LOG_FREQ: "3s"
      PUBLISH_TO_CONSOLE: "false"
    outputs:
      - name: subscriber
        component: kafka-server
        type: pubsub
        topic: "sample-topic"
    pubsub:
      kafka-server:
        type: pubsub.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: authRequired
            value: "false"
          - name: allowedTopics
            value: "sample-topic"
          - name: consumerID
            value: "producer"
