apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: autoscaling-subscriber
spec:
  version: "v1.0.0"
  image: openfunctiondev/v1beta1-autoscaling-subscriber:latest
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/builder-go:latest
    env:
      FUNC_NAME: "Subscriber"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Async/pubsub/subscriber"
  serving:
    runtime: "Async"
    scaleOptions:
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: "sample-topic"
                bootstrapServers: kafka-server-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: autoscaling-subscriber
                lagThreshold: "10"
    template:
      containers:
        - name: function
          imagePullPolicy: Always
    inputs:
      - name: producer
        component: kafka-server
        type: pubsub
        topic: "sample-topic"
    pubsub:
      kafka-server:
        type: pubsub.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: authRequired
            value: "false"
          - name: allowedTopics
            value: "sample-topic"
          - name: consumerID
            value: "autoscaling-subscriber"
