
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: functions.core.openfunction.io
spec:
  group: core.openfunction.io
  names:
    kind: Function
    listKind: FunctionList
    plural: functions
    shortNames:
    - fn
    singular: function
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Function is the Schema for the functions API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FunctionSpec defines the desired state of Function
            properties:
              build:
                description: Information needed to build a function
                properties:
                  builder:
                    description: Cloud Native Buildpacks builders
                    type: string
                  params:
                    additionalProperties:
                      type: string
                    description: Environment params to pass to the builder
                    type: object
                  registry:
                    description: Image registry of the function image
                    properties:
                      account:
                        description: Image registry account including username and
                          password
                        properties:
                          key:
                            description: The key of the secret to select from.  Must
                              be a valid secret key.
                            type: string
                          name:
                            description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                              TODO: Add other useful fields. apiVersion, kind, uid?'
                            type: string
                          optional:
                            description: Specify whether the Secret or its key must
                              be defined
                            type: boolean
                        required:
                        - key
                        type: object
                      url:
                        description: Image registry url
                        type: string
                    type: object
                  srcRepo:
                    description: Function Source code repository
                    properties:
                      deleteExisting:
                        description: 'Clean out the contents of the repo''s destination
                          directory if it already exists before cloning the repo there
                          (default: true)'
                        type: string
                      depth:
                        description: 'Performs a shallow clone where only the most
                          recent commit(s) will be fetched (default: 1)'
                        type: integer
                      gitInitImage:
                        description: 'The image used where the git-init binary is
                          (default: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.17.3")'
                        type: string
                      httpProxy:
                        description: 'Git HTTP proxy server for non-SSL requests (default:
                          "")'
                        type: string
                      httpsProxy:
                        description: 'Git HTTPS proxy server for SSL requests (default:
                          "")'
                        type: string
                      noProxy:
                        description: 'Git no proxy - opt out of proxying HTTP/HTTPS
                          requests (default: "")'
                        type: string
                      refspec:
                        description: Git refspec to fetch before checking out revision
                          (default:"")
                        type: string
                      revision:
                        description: Git revision to checkout (branch, tag, sha, refâ€¦)
                          (default:"")
                        type: string
                      sourceSubPath:
                        description: A subpath within the `source` input where the
                          source to build is located.
                        type: string
                      sslVerify:
                        description: 'Defines if http.sslVerify should be set to true
                          or false in the global git config (default: true)'
                        type: boolean
                      subDirectory:
                        description: 'Subdirectory inside the "output" workspace to
                          clone the git repo into (default: "")'
                        type: string
                      submodules:
                        description: 'Defines if the resource should initialize and
                          fetch the submodules (default: true)'
                        type: boolean
                      url:
                        description: Git url to clone
                        type: string
                      verbose:
                        description: 'Log the commands that are executed during git-clone''s
                          operation (default: true)'
                        type: boolean
                    required:
                    - url
                    type: object
                required:
                - builder
                - registry
                - srcRepo
                type: object
              image:
                description: Function image name
                type: string
              port:
                description: The port on which the function will be invoked
                format: int32
                type: integer
              serving:
                description: Information needed to run a function
                properties:
                  params:
                    additionalProperties:
                      type: string
                    description: Parameters to pass to the serving. All parameters
                      will be injected into the pod as environment variables. Function
                      code can use these parameters by getting environment variables
                    type: object
                  runtime:
                    description: Function runtime such as Knative or KEDA
                    type: string
                type: object
              version:
                description: Function version in format like v1.0.0
                type: string
            required:
            - build
            - image
            type: object
          status:
            description: FunctionStatus defines the observed state of Function
            properties:
              phase:
                type: string
              state:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
