---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: triggers.events.openfunction.io
spec:
  group: events.openfunction.io
  names:
    kind: Trigger
    listKind: TriggerList
    plural: triggers
    singular: trigger
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.eventBus
      name: EventBus
      type: string
    - jsonPath: .status.conditions[-1].type
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Trigger is the Schema for the triggers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TriggerSpec defines the desired state of Trigger
            properties:
              eventBus:
                description: EventBus allows you to specify a specific EventBus to
                  be used instead of the "default" one
                type: string
              inputs:
                additionalProperties:
                  properties:
                    event:
                      description: Event, name of event
                      type: string
                    eventSource:
                      description: EventSource, name of EventSource
                      type: string
                    namespace:
                      description: Namespace, namespace of EventSource, default to
                        namespace of Trigger
                      type: string
                  required:
                  - event
                  - eventSource
                  type: object
                description: Inputs defines the event sources associated with the
                  Trigger
                type: object
              logLevel:
                description: The logging level of the event source handler, e.g. "1",
                  "2", "3". The level increases as the value increases, default is
                  "1".
                type: string
              subscribers:
                description: Subscribers defines the subscribers associated with the
                  Trigger
                items:
                  properties:
                    condition:
                      description: Condition for judging events
                      type: string
                    deadLetterSink:
                      description: SinkSpec specifies the receiver of the events an
                        EventSource received, sinks in the Uri format have higher
                        priority than sinks in Reference format.
                      properties:
                        ref:
                          properties:
                            apiVersion:
                              description: API version of the referent.
                              type: string
                            kind:
                              description: Kind of the referent.
                              type: string
                            name:
                              description: Name of the referent.
                              type: string
                            namespace:
                              description: Namespace of the referent.
                              type: string
                          required:
                          - apiVersion
                          - kind
                          - name
                          type: object
                        uri:
                          type: string
                      type: object
                    deadLetterTopic:
                      type: string
                    sink:
                      description: Sink and DeadLetterSink are used to handle subscribers
                        who use the synchronous call method
                      properties:
                        ref:
                          properties:
                            apiVersion:
                              description: API version of the referent.
                              type: string
                            kind:
                              description: Kind of the referent.
                              type: string
                            name:
                              description: Name of the referent.
                              type: string
                            namespace:
                              description: Namespace of the referent.
                              type: string
                          required:
                          - apiVersion
                          - kind
                          - name
                          type: object
                        uri:
                          type: string
                      type: object
                    topic:
                      description: Topic and DeadLetterTopic are used to handle subscribers
                        who use the asynchronous call method
                      type: string
                  required:
                  - condition
                  type: object
                type: array
            required:
            - eventBus
            - inputs
            - subscribers
            type: object
          status:
            description: TriggerStatus defines the observed state of Trigger
            properties:
              conditions:
                items:
                  properties:
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      enum:
                      - EventSourceFunctionCreated
                      - ErrorCreatingEventSource
                      - ErrorCreatingEventSourceFunction
                      - EventSourceIsReady
                      - ErrorConfiguration
                      - ErrorToFindExistEventBus
                      - ErrorGenerateComponent
                      - ErrorGenerateScaledObject
                      - PendingCreation
                      - ErrorToFindTriggerSubscribers
                      - ErrorCreatingTrigger
                      - TriggerIsReady
                      - ErrorCreatingTriggerFunction
                      - TriggerFunctionCreated
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    timestamp:
                      description: Timestamp of the condition
                      type: string
                    type:
                      description: Type of condition
                      enum:
                      - Created
                      - Error
                      - Pending
                      - Unknown
                      - Terminating
                      - Terminated
                      - Ready
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
