
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: builders.openfunction.io
spec:
  group: openfunction.io
  names:
    kind: Builder
    listKind: BuilderList
    plural: builders
    shortNames:
    - fb
    singular: builder
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Builder is the Schema for the builders API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BuilderSpec defines the desired state of Builder
          properties:
            builder:
              description: Cloud Native Buildpacks builders
              type: string
            funcName:
              description: The name of the exported function to be invoked in function
                code
              type: string
            funcType:
              description: Function type such as HTTP or CloudEvent
              type: string
            funcVersion:
              description: Function version in format like v1.0.0
              type: string
            image:
              description: Function image name
              type: string
            registry:
              description: Image registry of the function image
              properties:
                account:
                  description: Image registry account including username and password
                  properties:
                    key:
                      description: The key of the secret to select from.  Must be
                        a valid secret key.
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                    optional:
                      description: Specify whether the Secret or its key must be defined
                      type: boolean
                  required:
                  - key
                  type: object
                url:
                  description: Image registry url
                  type: string
              type: object
            source:
              description: Git repository info of a function
              properties:
                deleteExisting:
                  description: 'Clean out the contents of the repo''s destination
                    directory if it already exists before cloning the repo there (default:
                    true)'
                  type: string
                depth:
                  description: 'Performs a shallow clone where only the most recent
                    commit(s) will be fetched (default: 1)'
                  type: integer
                gitInitImage:
                  description: 'The image used where the git-init binary is (default:
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.17.3")'
                  type: string
                httpProxy:
                  description: 'Git HTTP proxy server for non-SSL requests (default:
                    "")'
                  type: string
                httpsProxy:
                  description: 'Git HTTPS proxy server for SSL requests (default:
                    "")'
                  type: string
                noProxy:
                  description: 'Git no proxy - opt out of proxying HTTP/HTTPS requests
                    (default: "")'
                  type: string
                refspec:
                  description: Git refspec to fetch before checking out revision (default:"")
                  type: string
                revision:
                  description: Git revision to checkout (branch, tag, sha, refâ€¦) (default:"")
                  type: string
                sourceSubPath:
                  description: A subpath within the `source` input where the source
                    to build is located.
                  type: string
                sslVerify:
                  description: 'Defines if http.sslVerify should be set to true or
                    false in the global git config (default: true)'
                  type: boolean
                subDirectory:
                  description: 'Subdirectory inside the "output" workspace to clone
                    the git repo into (default: "")'
                  type: string
                submodules:
                  description: 'Defines if the resource should initialize and fetch
                    the submodules (default: true)'
                  type: boolean
                url:
                  description: Git url to clone
                  type: string
                verbose:
                  description: 'Log the commands that are executed during git-clone''s
                    operation (default: true)'
                  type: boolean
              required:
              - url
              type: object
          required:
          - builder
          - funcName
          - funcType
          - funcVersion
          - image
          - registry
          - source
          type: object
        status:
          description: BuilderStatus defines the observed state of Builder
          properties:
            phase:
              type: string
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
